language:
  - ruby
  - node_js

rvm: 2.4.1

node_js: 8

cache:
  bundler: true
  yarn: true
  directories:
    - client/node_modules

install:
  - ./bin/setup

before_script:
  - (cd client && yarn)

script:
  - bundle exec rspec
  - (cd client && yarn lint && yarn test)
